#!/bin/bash
#SBATCH --job-name='mace-5'
#SBATCH --account=silkem
#SBATCH --time=13-00:00:00
#SBATCH --output=./mace_logs/log/5.log
#SBATCH --error=./mace_logs/error/5.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --hint=multithread
#SBATCH --mem=16G
#SBATCH --partition=normal

python /STER/silkem/MACE/src/mace/CSE_0D/mace_training_routine.py in_file_5
