C
C  SUBROUTINE TO CALL FREEZE-OUT TERMS IS NEEDED
C
      SUBROUTINE FREEZE(N,Y,YDOT)
      DOUBLE PRECISION T,F,D,K,Y,YDOT,X,TOTAL,ACCR,HNR,HLOSS,GR,DN,MASS,
     *  SH,S
      INTEGER N,IFREEZE
      DIMENSION Y(N),YDOT(N),K(10000),X(10),TOTAL(10),MASS(468),S(468)
      COMMON/BL1/ K,X,TOTAL,GR,DN,ACCR,HNR,IFREEZE
      COMMON/BL10/ MASS,SH
      DO 2 I = 1,N
      S(I) = 1.0
 2    CONTINUE
C SET S(I) = 0.0 FOR H, He AND RELATED IONS
      DO 3 I = 1,9
      S(I) = 0.0
 3    CONTINUE
      DO 4 I = 1,N
      YDOT(I) = YDOT(I)-(ACCR*(S(I)/SH)*(1.0/MASS(I))**0.5)*Y(I)
 4    CONTINUE
      RETURN
      END